version: "3.7"
services:
    db:
        image: mariadb:latest
        container_name: db
        env_file:
            - ./.env.prod.db
        volumes:
        - sql_data:/var/lib/mysql/data/
    api:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        expose:
            - 8000
        command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/api/static
        env_file:
            - ./.env.prod
        depends_on:
            - db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/api/static
        ports:
            - 8000:80
        depends_on:
            - api
volumes:
    sql_data:
    static_volume: