version: "3.7"
services:
    db:
        image: mariadb:latest
        container_name: db
        environment:
        - MYSQL_DATABASE=docker
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=root
        volumes:
        - sql_data:/var/lib/mysql/data/
    api:
        build:  ./
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./.env
        depends_on:
            - db
volumes:
    sql_data: