version: "3.7"
services:
    api:
        build:  ./
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: mariadb:latest
        restart: always
        environment:
        - MYSQL_PORT=3306
        - MYSQL_DATABASE=docker
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
        volumes:
        - sql_data:/var/lib/mysql/data/

volumes:
    sql_data: