version: "3.7"
services:
    api:
        build:  ./
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./.env